<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="eon-swapnili" name="RegressionTest" tests="2" failures="1" timestamp="9 Jan 2024 11:43:49 GMT" time="123.873" errors="0">
  <testcase name="TS003_VerifyIMCEventsCalendarViewTest" time="64.956" classname="lasvegasmarket_PROD.EvenntsAndWebinar"/>
  <testcase name="TS004_VerifyIMCEventsEventsListTest" time="33.38" classname="lasvegasmarket_PROD.EvenntsAndWebinar">
    <failure type="java.lang.AssertionError" message="expected [35] but found [50]">
      <![CDATA[java.lang.AssertionError: expected [35] but found [50]
	at lasvegasmarket_PROD.EvenntsAndWebinar.TS004_VerifyIMCEventsEventsListTest(EvenntsAndWebinar.java:448)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- TS004_VerifyIMCEventsEventsListTest -->
</testsuite> <!-- RegressionTest -->
