<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="eon-swapnili" name="lasvegasmarket_UAT.Events" tests="9" failures="1" timestamp="30 Jul 2024 10:43:10 GMT" time="497.675" errors="0">
  <testcase name="TS007_VerifyExhibitorEventsCalendarViewTest" time="68.361" classname="lasvegasmarket_UAT.Events"/>
  <testcase name="TS002_VerifyIMCEventsSearchbarTest" time="23.613" classname="lasvegasmarket_UAT.Events"/>
  <testcase name="TS006_VerifyExhibitorEventsSearchbarTest" time="23.511" classname="lasvegasmarket_UAT.Events"/>
  <testcase name="TS008_VerifyExhibitorEventsListTest" time="64.980" classname="lasvegasmarket_UAT.Events"/>
  <testcase name="TS004_VerifyIMCEventsEventsListTest" time="57.152" classname="lasvegasmarket_UAT.Events">
    <failure type="java.lang.AssertionError" message="expected [2] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [3]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:372)
	at org.testng.Assert.assertEquals(Assert.java:382)
	at lasvegasmarket_UAT.Events.TS004_VerifyIMCEventsEventsListTest(Events.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- TS004_VerifyIMCEventsEventsListTest -->
  <testcase name="TS003_VerifyIMCEventsCalendarViewTest" time="88.382" classname="lasvegasmarket_UAT.Events"/>
  <testcase name="TS005_VerifyIMCEventsEventDetailstTest" time="130.308" classname="lasvegasmarket_UAT.Events"/>
  <testcase name="TS001_VerifyEventsAndWebinarsOverviewTest" time="16.944" classname="lasvegasmarket_UAT.Events"/>
  <testcase name="TS009_VerifyExhibitorEventsDetailstTest" time="24.424" classname="lasvegasmarket_UAT.Events"/>
</testsuite> <!-- lasvegasmarket_UAT.Events -->
